---
provisioner:
  name: shell
  data_path: .

driver:
  name: vagrant
  ssh:
    insert_key: false

verifier:
  ruby_bindir: /usr/bin

platforms:
- name: openshift
  driver:
    box: bento/ubuntu-16.04

suites:
- name: s2i-wildfly