#!/bin/bash -e
#
# S2I run script for the 'test' image.
# The run script executes the server that runs your application.
#
# For more information see the documentation:
#	https://github.com/openshift/source-to-image/blob/master/docs/builder_image.md
#

export DT_ONEAGENT_FOR=java
. /usr/libexec/s2i/dynatrace-monitoring-incl.sh

exec $EXEC_CMD_PREFIX <start your server here>